dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm-3.24
  - nightly
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: hhvm-3.24
    - php: nightly
  fast_finish: true
  include:
    - name: "PHP: 7.3 - Guzzle 7 beta"
      php: 7.3
      env: COMPOSER_OPTS="--no-interaction"
      before_install:
        - composer require "guzzlehttp/guzzle:^7.0@beta"

sudo: false

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  # Setup environment variables for testing
  - export AWS_ACCESS_KEY_ID=foo
  - export AWS_SECRET_ACCESS_KEY=bar
  - export AWS_CSM_ENABLED=false

  # Build job specific tweaks
  - >
    if [ $(phpenv version-name) == "5.5" ]; then
      rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    fi

  - >
    if [ $(phpenv version-name) != "hhvm-3.24" ] && [ $(phpenv version-name) != "nightly" ]; then
      echo "xdebug.overload_var_dump = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi

  - >
    if { [ $(phpenv version-name) == "7.2" ] || [ $(phpenv version-name) == "7.3" ] || [$(phpenv version-name) == "7.4"]; } && [ -v COMPOSER_OPTS ]; then
      composer require --dev phpunit/phpunit "^5.7.11"
    fi

  # Resolve dependencies
  - composer --version
  - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source
  - composer show guzzlehttp/guzzle

script:
  # Unit tests
  - make test

  # Static analysis
  - >
    test_versions=("7.1" "7.2" "7.3" "7.4");
    if [[ " ${test_versions[@]} " =~ " $(phpenv version-name) " ]] && [ -z $COMPOSER_OPTS ]; then
      composer require --dev nette/neon "^3.0"
      composer require --dev phpstan/phpstan "0.12.11"
      vendor/bin/phpstan analyse src
    fi

  # Package generation
  - if [ -z "$COMPOSER_OPTS" ]; then make package; fi

after_success:
  # Code coverage report
  - >
    if [ $(phpenv version-name) == "7.1" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
